# Generated by Django 5.2.7 on 2025-11-03 00:28

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('Workshop', 'Workshop'), ('Palestra', 'Palestra'), ('Networking', 'Networking'), ('Curso', 'Curso')], max_length=20)),
                ('itens_incluidos', models.TextField(blank=True, default='', help_text='Digite um item por linha')),
                ('data_evento', models.DateTimeField()),
                ('endereco', models.CharField(max_length=300)),
                ('local_especifico', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidade_maxima', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_deposito', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('permite_transferencia', models.BooleanField(default=True)),
                ('politica_cancelamento', models.TextField(default='Cancelamento gratuito até 24h antes do evento')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='eventos/capas/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_evento',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('score', models.FloatField(default=5)),
                ('profile_photo', models.ImageField(blank=True, default='profile_photos/user.jpg', null=True, upload_to='profile_photos/')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, null=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=10, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('documento_foto', models.ImageField(blank=True, null=True, upload_to='documentos/')),
                ('documento_verificado', models.CharField(choices=[('pendente', 'Pendente'), ('verificando', 'Verificando'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'api_customuser',
            },
        ),
        migrations.CreateModel(
            name='EventoAnalytics',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='api.evento')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, help_text='Custo total de organização do evento', max_digits=10)),
                ('receita_total', models.DecimalField(decimal_places=2, default=0, help_text='Receita total gerada', max_digits=10)),
                ('roi', models.DecimalField(decimal_places=2, default=0, help_text='Return on Investment calculado automaticamente', max_digits=10)),
                ('total_visualizacoes', models.IntegerField(default=0)),
                ('visualizacoes_unicas', models.IntegerField(default=0)),
                ('total_interacoes_simulador', models.IntegerField(default=0)),
                ('tempo_medio_simulador', models.DecimalField(decimal_places=2, default=0, help_text='Tempo médio de interação com simuladores em segundos', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics do Evento',
                'verbose_name_plural': 'Analytics dos Eventos',
                'db_table': 'api_eventoanalytics',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota (0-5)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api.evento')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'api_avaliacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo_inscricao', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf_inscricao', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone_inscricao', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email_inscricao', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('transferida', 'Transferida'), ('lista_espera', 'Lista de Espera')], default='pendente', max_length=20)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX')], max_length=20)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20)),
                ('checkin_realizado', models.BooleanField(default=False)),
                ('data_checkin', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('aceita_termos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='api.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_inscricao',
                'ordering': ['-created_at'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='InteracaoSimulador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_simulador', models.CharField(help_text="Nome ou tipo do simulador (ex: 'Simulador de ROI', 'Quiz')", max_length=100)),
                ('duracao_segundos', models.IntegerField(default=0, help_text='Duração da interação em segundos')),
                ('concluiu', models.BooleanField(default=False, help_text='Se o usuário concluiu a interação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_simulador', to='api.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_simulador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação com Simulador',
                'verbose_name_plural': 'Interações com Simuladores',
                'db_table': 'api_interacaosimulador',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Enviada'), ('accepted', 'Aceita'), ('denied', 'Negada'), ('cancelled', 'Cancelada')], default='sent', max_length=10)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='api.inscricao')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferir Inscrição',
                'verbose_name_plural': 'Transfer. de Inscrição',
                'db_table': 'api_transferrequest',
            },
        ),
        migrations.CreateModel(
            name='VisualizacaoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do visitante', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent do navegador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='api.evento')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que visualizou (pode ser nulo para visitantes não autenticados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de Evento',
                'verbose_name_plural': 'Visualizações de Eventos',
                'db_table': 'api_visualizacaoevento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_favorite',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('fila', 'Fila'), ('notificado', 'Notificado'), ('aceitou', 'Aceitou'), ('expirado', 'Expirado')], default='fila', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='api.evento')),
                ('inscricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='api.inscricao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entradas da Lista de Espera',
                'verbose_name_plural': 'Entradas da Lista de Espera',
                'db_table': 'api_waitlistentry',
                'ordering': ['created_at'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
