# Generated by Django 5.2.7 on 2025-11-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20251030_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoanalytics',
            name='tempo_medio_simulador',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tempo médio de interação com simuladores em segundos', max_digits=10),
        ),
        migrations.AddField(
            model_name='eventoanalytics',
            name='visualizacoes_unicas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='eventoanalytics',
            table='api_eventoanalytics',
        ),
        migrations.AlterModelTable(
            name='interacaosimulador',
            table='api_interacaosimulador',
        ),
        migrations.AlterModelTable(
            name='visualizacaoevento',
            table='api_visualizacaoevento',
        ),
    ]
