# Generated by Django 5.2.7 on 2025-11-03 06:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('Workshop', 'Workshop'), ('Palestra', 'Palestra'), ('Networking', 'Networking'), ('Curso', 'Curso')], max_length=20)),
                ('itens_incluidos', models.TextField(blank=True, default='', help_text='Digite um item por linha')),
                ('data_evento', models.DateTimeField()),
                ('endereco', models.CharField(max_length=300)),
                ('local_especifico', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidade_maxima', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_deposito', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('permite_transferencia', models.BooleanField(default=True)),
                ('politica_cancelamento', models.TextField(default='Cancelamento gratuito até 24h antes do evento')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='eventos/capas/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_evento',
                'ordering': ['-data_evento'],
            },
        ),
    ]
