# Generated by Django 5.2.7 on 2025-11-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='qr_code_pix',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/qrcodes_pix/'),
        ),
    ]
