# Generated by Django 5.2.8 on 2025-11-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_qr_code_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria_customizada',
            field=models.CharField(blank=True, help_text="Categoria personalizada quando 'Outro' é selecionado", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Palestra', 'Palestra'), ('Networking', 'Networking'), ('Curso', 'Curso'), ('Outro', 'Outro')], max_length=20),
        ),
    ]
