# Generated by Django 5.2.8 on 2025-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_categoria_customizada_alter_evento_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias',
            field=models.JSONField(default=list, help_text='Lista de categorias do evento'),
        ),
    ]
