# Generated by Django 5.2.8 on 2025-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_evento_categoria_evento_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='categoria_customizada',
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias_customizadas',
            field=models.JSONField(blank=True, default=list, help_text="Lista de categorias personalizadas quando 'Outro' é selecionado"),
        ),
    ]
