# Generated by Django 5.2.7 on 2025-11-03 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('inscricoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('fila', 'Fila'), ('notificado', 'Notificado'), ('aceitou', 'Aceitou'), ('expirado', 'Expirado')], default='fila', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='eventos.evento')),
                ('inscricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='inscricoes.inscricao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entradas da Lista de Espera',
                'verbose_name_plural': 'Entradas da Lista de Espera',
                'db_table': 'api_waitlistentry',
                'ordering': ['created_at'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
