# Generated by Django 5.2.6 on 2025-09-29 00:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/user.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
