# Generated by Django 5.2.6 on 2025-09-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_profile_photo_evento_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='itens_incluidos',
            field=models.TextField(blank=True, default='', help_text='Digite um item por linha'),
        ),
    ]
