# Generated by Django 5.2.6 on 2025-09-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_profile_photo_evento_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='cpf_inscricao',
            field=models.CharField(default='00000000000', max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='email_inscricao',
            field=models.EmailField(default='Nome não informado', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='nome_completo_inscricao',
            field=models.CharField(default='00000000000', max_length=200, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='telefone_inscricao',
            field=models.CharField(default='email@temporario.com', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
