# Generated by Django 5.2.7 on 2025-10-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_avaliacao'),
        ('api', '0003_evento_itens_incluidos'),
    ]

    operations = [
    ]
