# Generated by Django 5.2.7 on 2025-10-02 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_0002_avaliacao_0003_evento_itens_incluidos'),
    ]

    operations = [
        # Drop legacy tables if they exist (we already have Evento/Inscricao in the DB)
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS api_registration CASCADE;
            DROP TABLE IF EXISTS api_event CASCADE;
            """
        ),
        # Ensure latitude and longitude exist (no-op if already present)
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name='api_evento' AND column_name='latitude'
                ) THEN
                    ALTER TABLE api_evento ADD COLUMN latitude double precision;
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name='api_evento' AND column_name='longitude'
                ) THEN
                    ALTER TABLE api_evento ADD COLUMN longitude double precision;
                END IF;
            END$$;
            """
        ),
        # Try to alter categoria choices if necessary; this is safe to run even if the choices are equal
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Palestra', 'Palestra'), ('Networking', 'Networking'), ('Curso', 'Curso')], max_length=20),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'evento')},
            },
        ),
        # Ensure legacy tables exist (no-op if already present) so DeleteModel can run cleanly
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS api_event (id bigint PRIMARY KEY);
            CREATE TABLE IF NOT EXISTS api_registration (id bigint PRIMARY KEY);
            """
        ),
        # Keep DeleteModel operations so migration state reflects removal of legacy models
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
