# Generated by Django 5.2.6 on 2025-10-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transferrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'verbose_name': 'Transferir Inscrição', 'verbose_name_plural': 'Transfer. de Inscrição'},
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
