# Generated by Django 5.2.6 on 2025-10-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='documento_foto',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='documento_verificado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('verificando', 'Verificando'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=10, null=True),
        ),
    ]
