# Generated by Django 5.2.7 on 2025-10-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_documento_foto_and_more'),
        ('api', '0009_eventoanalytics_interacaosimulador_and_more'),
    ]

    operations = [
    ]
