# Generated by Django 5.2.7 on 2025-11-02 18:49
# Migration: Restringe método de pagamento para apenas PIX
# Remove outras opções de pagamento (cartão, boleto) mantendo apenas PIX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20251030_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX')], default='pix', max_length=20),
        ),
    ]
