# Generated by Django 5.2.7 on 2025-11-02 22:28
# Migration: Adiciona campo qr_code_pix ao modelo Evento
# Permite que organizadores façam upload do QR Code PIX para pagamento das inscrições

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_metodo_pagamento_only_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='qr_code_pix',
            field=models.ImageField(blank=True, help_text='QR Code PIX para pagamento do evento', null=True, upload_to='eventos/qrcodes_pix/'),
        ),
    ]
