# Generated by Django 5.2.7 on 2025-11-03 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vaga_lista_espera', 'Vaga na Lista de Espera'), ('evento_proximo', 'Evento Próximo'), ('transferencia_aprovada', 'Transferência Aprovada'), ('transferencia_recusada', 'Transferência Recusada'), ('transferencia_recebida', 'Solicitação de Transferência Recebida'), ('inscricao_confirmada', 'Inscrição Confirmada'), ('checkin_lembrete', 'Lembrete de Check-in'), ('avaliacao_pendente', 'Avaliação Pendente'), ('documento_aprovado', 'Documento Aprovado'), ('documento_rejeitado', 'Documento Rejeitado'), ('sistema', 'Notificação do Sistema')], max_length=50, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('link', models.CharField(blank=True, help_text='Link para redirecionar quando a notificação for clicada', max_length=500, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='notificacoe_usuario_3c2963_idx'), models.Index(fields=['usuario', 'lida'], name='notificacoe_usuario_a5894e_idx')],
            },
        ),
    ]
