# Generated by Django 5.2.7 on 2025-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vaga_lista_espera', 'Vaga na Lista de Espera'), ('evento_proximo', 'Evento Próximo'), ('transferencia_aprovada', 'Transferência Aprovada'), ('transferencia_recusada', 'Transferência Recusada'), ('transferencia_recebida', 'Solicitação de Transferência Recebida'), ('transferencia', 'Transferência'), ('inscricao_confirmada', 'Inscrição Confirmada'), ('checkin_lembrete', 'Lembrete de Check-in'), ('avaliacao_pendente', 'Avaliação Pendente'), ('documento_aprovado', 'Documento Aprovado'), ('documento_rejeitado', 'Documento Rejeitado'), ('favorito_novo_evento', 'Novo Evento de Favorito'), ('evento_cancelado', 'Evento Cancelado'), ('sistema', 'Notificação do Sistema')], max_length=50, verbose_name='Tipo'),
        ),
    ]
