# Generated by Django 5.2.7 on 2025-11-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_add_metadata'),
        ('notificacoes', '0002_alter_notificacao_tipo'),
    ]

    operations = [
    ]
