# Generated by Django 5.2.7 on 2025-11-03 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo_inscricao', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf_inscricao', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone_inscricao', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email_inscricao', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('transferida', 'Transferida'), ('lista_espera', 'Lista de Espera')], default='pendente', max_length=20)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX')], max_length=20)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20)),
                ('checkin_realizado', models.BooleanField(default=False)),
                ('data_checkin', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('aceita_termos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_inscricao',
                'ordering': ['-created_at'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
