# Generated by Django 5.2.7 on 2025-11-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='comprovante_pagamento',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes_pagamento/', verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='id_transacao_gateway',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID da Transação'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='observacoes_pagamento',
            field=models.TextField(blank=True, null=True, verbose_name='Observações sobre o Pagamento'),
        ),
    ]
