# Generated by Django 5.2.7 on 2025-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_inscricao_comprovante_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='expira_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que a inscrição pendente expira', null=True),
        ),
    ]
