# Generated by Django 5.2.8 on 2025-11-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscricoes", "0003_inscricao_expira_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscricao",
            name="metodo_pagamento",
            field=models.CharField(
                choices=[
                    ("cartao_credito", "Cartão de Crédito"),
                    ("cartao_debito", "Cartão de Débito"),
                ],
                max_length=20,
            ),
        ),
    ]
