# Generated by Django 5.2.7 on 2025-11-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0001_initial'),
    ]

    operations = [
    ]
