# Generated by Django 5.2.7 on 2025-11-03 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAnalytics',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='eventos.evento')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, help_text='Custo total de organização do evento', max_digits=10)),
                ('receita_total', models.DecimalField(decimal_places=2, default=0, help_text='Receita total gerada', max_digits=10)),
                ('roi', models.DecimalField(decimal_places=2, default=0, help_text='Return on Investment calculado automaticamente', max_digits=10)),
                ('total_visualizacoes', models.IntegerField(default=0)),
                ('visualizacoes_unicas', models.IntegerField(default=0)),
                ('total_interacoes_simulador', models.IntegerField(default=0)),
                ('tempo_medio_simulador', models.DecimalField(decimal_places=2, default=0, help_text='Tempo médio de interação com simuladores em segundos', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics do Evento',
                'verbose_name_plural': 'Analytics dos Eventos',
                'db_table': 'api_eventoanalytics',
            },
        ),
        migrations.CreateModel(
            name='InteracaoSimulador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_simulador', models.CharField(help_text="Nome ou tipo do simulador (ex: 'Simulador de ROI', 'Quiz')", max_length=100)),
                ('duracao_segundos', models.IntegerField(default=0, help_text='Duração da interação em segundos')),
                ('concluiu', models.BooleanField(default=False, help_text='Se o usuário concluiu a interação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_simulador', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_simulador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação com Simulador',
                'verbose_name_plural': 'Interações com Simuladores',
                'db_table': 'api_interacaosimulador',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualizacaoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do visitante', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent do navegador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='eventos.evento')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que visualizou (pode ser nulo para visitantes não autenticados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de Evento',
                'verbose_name_plural': 'Visualizações de Eventos',
                'db_table': 'api_visualizacaoevento',
                'ordering': ['-created_at'],
            },
        ),
    ]
